### ISSUE TITLE
Pip Version Gives Error

### ISSUE THREAD

**Issue by whatamithinking** [ahmetkotan/yapi#9]
FYI - 
I got the following error when trying to install the pip version. The GitHub version works great, but not the pip version.

Namespace(error=Namespace(code=400, errors=[Namespace(domain='global', location='order', locationType='parameter', message="Invalid string value: 'None'. Allowed values: [date, rating, relevance, title, videocount, viewcount]", reason='invalidParameter')], message="Invalid string value: 'None'. Allowed values: [date, rating, relevance, title, videocount, viewcount]"))
>

**Comment by ahmetkotan** [comment]
Thank your feedback again :) 

I updated pip package.
[https://pypi.org/project/yapi/](https://pypi.org/project/yapi/)
